# Generated by Django 3.0 on 2020-02-23 16:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acheteur',
            fields=[
                ('numAcheteur', models.AutoField(primary_key=True, serialize=False)),
                ('nomAcheteur', models.CharField(max_length=30)),
                ('prenomAcheteur', models.CharField(max_length=30)),
                ('mailAcheteur', models.EmailField(max_length=254)),
                ('noteAcheteur', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('adresseAcheteur', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('numCategorie', models.AutoField(primary_key=True, serialize=False)),
                ('libelleCategorie', models.CharField(blank=True, choices=[('Emploi', 'Véhicules'), ('Vacances', 'Loisirs'), ('Mode', 'Multimédia'), ('Maison', 'Autre')], max_length=30)),
            ],
            options={
                'db_table': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('numVendeur', models.AutoField(primary_key=True, serialize=False)),
                ('nomVendeur', models.CharField(max_length=30)),
                ('prenomVendeur', models.CharField(max_length=30)),
                ('mailVendeur', models.EmailField(max_length=254)),
                ('noteVendeur', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'db_table': 'vendeur',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('numProduit', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=30)),
                ('desciption', models.TextField()),
                ('images', models.ImageField(upload_to=None)),
                ('prixBase', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('dateDebut', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de début de l'enchère")),
                ('dateFin', models.DateTimeField(verbose_name="Date de fin de l'enchère")),
                ('categorieFK', models.ForeignKey(db_column='numCategorie', on_delete=django.db.models.deletion.CASCADE, to='ProjetWeb.Categorie')),
                ('vendeurFK', models.ForeignKey(db_column='numVendeur', on_delete=django.db.models.deletion.CASCADE, to='ProjetWeb.Vendeur')),
            ],
        ),
        migrations.CreateModel(
            name='Enchere',
            fields=[
                ('numEnchere', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('commentaire', models.CharField(max_length=50)),
                ('acheteurFK', models.ForeignKey(db_column='numAcheteur', on_delete=django.db.models.deletion.CASCADE, to='ProjetWeb.Acheteur')),
                ('produitFK', models.ForeignKey(db_column='numProduit', on_delete=django.db.models.deletion.CASCADE, to='ProjetWeb.Produit')),
            ],
        ),
    ]
