# Generated by Django 3.0 on 2020-02-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetWeb', '0002_auto_20200223_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='images',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
