# Generated by Django 3.0 on 2020-02-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetWeb', '0003_auto_20200226_1331'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enchere',
            table='Enchere',
        ),
    ]
